title: Queensland Government Digital Capability Hub
description: A proof-of-concept DigComp 3.0 capability hub for Queensland Government employees.
url: "https://digcompqgov.github.io"
baseurl: "/digcomp.qld.gov.au"
markdown: kramdown
exclude:
  - README.md